name: Publish Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node & Build Assets
        run: |
          npm install
          npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /public_html/digitizematrix.co.in/digitizematrix/ # ✅ IMPORTANT
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            .env
